[2022-03-17 14:31:41,937] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_example_dag.load_songplays_fact_table manual__2022-03-17T06:31:30.657696+00:00 [queued]>
[2022-03-17 14:31:41,944] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_example_dag.load_songplays_fact_table manual__2022-03-17T06:31:30.657696+00:00 [queued]>
[2022-03-17 14:31:41,945] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 14:31:41,945] {taskinstance.py:1244} INFO - Starting attempt 1 of 3
[2022-03-17 14:31:41,945] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 14:31:41,953] {taskinstance.py:1264} INFO - Executing <Task(LoadFactOperator): load_songplays_fact_table> on 2022-03-17 06:31:30.657696+00:00
[2022-03-17 14:31:41,955] {standard_task_runner.py:52} INFO - Started process 23714 to run task
[2022-03-17 14:31:41,960] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'udac_example_dag', 'load_songplays_fact_table', 'manual__2022-03-17T06:31:30.657696+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmp7d33yz86', '--error-file', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmppr493_w3']
[2022-03-17 14:31:41,962] {standard_task_runner.py:77} INFO - Job 37: Subtask load_songplays_fact_table
[2022-03-17 14:31:42,019] {logging_mixin.py:109} INFO - Running <TaskInstance: udac_example_dag.load_songplays_fact_table manual__2022-03-17T06:31:30.657696+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-03-17 14:31:42,072] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_example_dag
AIRFLOW_CTX_TASK_ID=load_songplays_fact_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T06:31:30.657696+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-17T06:31:30.657696+00:00
[2022-03-17 14:31:42,073] {load_fact.py:86} INFO - Starting to truncate songplays
[2022-03-17 14:31:42,081] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-17 14:31:43,791] {dbapi.py:225} INFO - Running statement: 
        TRUNCATE TABLE "public"."songplays"
        , parameters: None
[2022-03-17 14:31:44,390] {load_fact.py:95} INFO - Starting to insert songplays
[2022-03-17 14:31:44,392] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-17 14:31:44,393] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-03-17 14:31:44,394] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-03-17 14:31:44,394] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-03-17 14:31:44,395] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 14:31:44,396] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 14:31:44,397] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-03-17 14:31:44,397] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-03-17 14:31:44,398] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 14:31:44,399] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 14:31:44,399] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 14:31:44,401] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 14:31:44,409] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-17 14:31:45,789] {dbapi.py:225} INFO - Running statement: 
        INSERT INTO "public"."songplays" (playid, start_time, userid, level, songid, artistid, sessionid, location, user_agent)
 <class 'helpers.sql_queries.SqlQueries'>.songplays_table_insert
        , parameters: None
[2022-03-17 14:31:46,431] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_fact.py", line 72, in execute
    self.load_songplays_fact_table(redshift_hook, context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_fact.py", line 107, in load_songplays_fact_table
    redshift_hook.run(insert_fact_data)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "<"
LINE 3:  <class 'helpers.sql_queries.SqlQueries'>.songplays_table_in...
         ^

[2022-03-17 14:31:46,445] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=load_songplays_fact_table, execution_date=20220317T063130, start_date=20220317T063141, end_date=20220317T063146
[2022-03-17 14:31:46,455] {standard_task_runner.py:89} ERROR - Failed to execute job 37 for task load_songplays_fact_table
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_fact.py", line 72, in execute
    self.load_songplays_fact_table(redshift_hook, context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_fact.py", line 107, in load_songplays_fact_table
    redshift_hook.run(insert_fact_data)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "<"
LINE 3:  <class 'helpers.sql_queries.SqlQueries'>.songplays_table_in...
         ^

[2022-03-17 14:31:46,484] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-17 14:31:46,519] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
