[2022-03-19 21:32:40,003] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_new_v1_dag.load_songplays_fact_table manual__2022-03-19T13:29:34.726733+00:00 [queued]>
[2022-03-19 21:32:40,013] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_new_v1_dag.load_songplays_fact_table manual__2022-03-19T13:29:34.726733+00:00 [queued]>
[2022-03-19 21:32:40,014] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-19 21:32:40,014] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-19 21:32:40,014] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-19 21:32:40,028] {taskinstance.py:1264} INFO - Executing <Task(LoadFactOperator): load_songplays_fact_table> on 2022-03-19 13:29:34.726733+00:00
[2022-03-19 21:32:40,030] {standard_task_runner.py:52} INFO - Started process 37147 to run task
[2022-03-19 21:32:40,036] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'udac_new_v1_dag', 'load_songplays_fact_table', 'manual__2022-03-19T13:29:34.726733+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/udac_v1.py', '--cfg-path', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpol1d8j3r', '--error-file', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpjr0krga6']
[2022-03-19 21:32:40,039] {standard_task_runner.py:77} INFO - Job 43: Subtask load_songplays_fact_table
[2022-03-19 21:32:40,094] {logging_mixin.py:109} INFO - Running <TaskInstance: udac_new_v1_dag.load_songplays_fact_table manual__2022-03-19T13:29:34.726733+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-03-19 21:32:40,148] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_new_v1_dag
AIRFLOW_CTX_TASK_ID=load_songplays_fact_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-19T13:29:34.726733+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-19T13:29:34.726733+00:00
[2022-03-19 21:32:40,148] {load_fact.py:86} INFO - Starting to truncate songplays
[2022-03-19 21:32:40,156] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-19 21:32:41,335] {dbapi.py:225} INFO - Running statement: 
        TRUNCATE TABLE "public"."songplays"
        , parameters: None
[2022-03-19 21:32:41,843] {load_fact.py:95} INFO - Starting to insert songplays
[2022-03-19 21:32:41,850] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-19 21:32:41,851] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-03-19 21:32:41,852] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-03-19 21:32:41,852] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-03-19 21:32:41,853] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 21:32:41,854] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 21:32:41,855] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-03-19 21:32:41,856] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-03-19 21:32:41,856] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 21:32:41,857] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 21:32:41,858] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 21:32:41,859] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 21:32:41,866] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-19 21:32:42,925] {dbapi.py:225} INFO - Running statement: 
        INSERT INTO "public"."songplays" (['playid', 'start_time', 'userid', 'level', 'songid', 'artistid', 'sessionid', 'location', 'user_agent'])
 
        SELECT
                md5(events.sessionid || events.start_time) songplay_id,
                events.start_time,
                events.userid,
                events.level,
                songs.song_id,
                songs.artist_id,
                events.sessionid,
                events.location,
                events.useragent
                FROM (SELECT TIMESTAMP 'epoch' + ts/1000 * interval '1 second' AS start_time, *
            FROM staging_events
            WHERE page='NextSong') events
            LEFT JOIN staging_songs songs
            ON events.song = songs.title
                AND events.artist = songs.artist_name
                AND events.length = songs.duration
    
        , parameters: None
[2022-03-19 21:32:43,228] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_fact.py", line 72, in execute
    self.load_songplays_fact_table(redshift_hook, context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_fact.py", line 106, in load_songplays_fact_table
    redshift_hook.run(insert_fact_data)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "'playid'"
LINE 2:         INSERT INTO "public"."songplays" (['playid', 'start_...
                                                   ^

[2022-03-19 21:32:43,245] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_new_v1_dag, task_id=load_songplays_fact_table, execution_date=20220319T132934, start_date=20220319T133240, end_date=20220319T133243
[2022-03-19 21:32:43,257] {standard_task_runner.py:89} ERROR - Failed to execute job 43 for task load_songplays_fact_table
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_fact.py", line 72, in execute
    self.load_songplays_fact_table(redshift_hook, context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_fact.py", line 106, in load_songplays_fact_table
    redshift_hook.run(insert_fact_data)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/anaconda3/envs/airflow_project/lib/python3.9/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "'playid'"
LINE 2:         INSERT INTO "public"."songplays" (['playid', 'start_...
                                                   ^

[2022-03-19 21:32:43,301] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-19 21:32:43,349] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
