[2022-03-17 15:02:42,643] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_example_dag.task_group_Dimension_table.load_users_dim_table manual__2022-03-17T06:57:19.461149+00:00 [queued]>
[2022-03-17 15:02:42,724] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_example_dag.task_group_Dimension_table.load_users_dim_table manual__2022-03-17T06:57:19.461149+00:00 [queued]>
[2022-03-17 15:02:42,724] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 15:02:42,725] {taskinstance.py:1244} INFO - Starting attempt 2 of 3
[2022-03-17 15:02:42,725] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 15:02:42,736] {taskinstance.py:1264} INFO - Executing <Task(LoadDimensionOperator): task_group_Dimension_table.load_users_dim_table> on 2022-03-17 06:57:19.461149+00:00
[2022-03-17 15:02:42,739] {standard_task_runner.py:52} INFO - Started process 38300 to run task
[2022-03-17 15:02:42,747] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'udac_example_dag', 'task_group_Dimension_table.load_users_dim_table', 'manual__2022-03-17T06:57:19.461149+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpkuj3limz', '--error-file', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpp14h277a']
[2022-03-17 15:02:42,750] {standard_task_runner.py:77} INFO - Job 48: Subtask task_group_Dimension_table.load_users_dim_table
[2022-03-17 15:02:42,950] {logging_mixin.py:109} INFO - Running <TaskInstance: udac_example_dag.task_group_Dimension_table.load_users_dim_table manual__2022-03-17T06:57:19.461149+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-03-17 15:02:43,091] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_example_dag
AIRFLOW_CTX_TASK_ID=task_group_Dimension_table.load_users_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T06:57:19.461149+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-17T06:57:19.461149+00:00
[2022-03-17 15:02:43,098] {load_dimension.py:83} INFO - Starting to truncate users
[2022-03-17 15:02:43,203] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-17 15:02:44,517] {dbapi.py:225} INFO - Running statement: 
        TRUNCATE TABLE "public"."users"
        , parameters: None
[2022-03-17 15:02:45,216] {load_dimension.py:93} INFO - Starting to insert users
[2022-03-17 15:02:45,219] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-17 15:02:45,220] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-03-17 15:02:45,221] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-03-17 15:02:45,222] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-03-17 15:02:45,223] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 15:02:45,223] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 15:02:45,224] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-03-17 15:02:45,225] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-03-17 15:02:45,225] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 15:02:45,226] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 15:02:45,227] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 15:02:45,228] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 15:02:45,234] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-17 15:02:46,625] {dbapi.py:225} INFO - Running statement: 
        INSERT INTO "public"."users" (userid, first_name, last_name, gender,level)
 "
        SELECT distinct userid, firstname, lastname, gender, level
        FROM staging_events
        WHERE page='NextSong'
    "
        , parameters: None
[2022-03-17 15:02:47,017] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_dimension.py", line 67, in execute
    self.load_dimension_table(redshift_hook, context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_dimension.py", line 103, in load_dimension_table
    redshift_hook.run(insert_dimension_data)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near ""
        SELECT distinct userid, firstname, lastname, gender, level
        FROM staging_events
        WHERE page='NextSong'
    ""
LINE 3:  "
         ^

[2022-03-17 15:02:47,029] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=task_group_Dimension_table.load_users_dim_table, execution_date=20220317T065719, start_date=20220317T070242, end_date=20220317T070247
[2022-03-17 15:02:47,037] {standard_task_runner.py:89} ERROR - Failed to execute job 48 for task task_group_Dimension_table.load_users_dim_table
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_dimension.py", line 67, in execute
    self.load_dimension_table(redshift_hook, context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/load_dimension.py", line 103, in load_dimension_table
    redshift_hook.run(insert_dimension_data)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near ""
        SELECT distinct userid, firstname, lastname, gender, level
        FROM staging_events
        WHERE page='NextSong'
    ""
LINE 3:  "
         ^

[2022-03-17 15:02:47,057] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-17 15:02:47,090] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
